language: python
python:
- '2.7'
install:
- pip install slackclient
- pip install urllib3
script: "./unittests"
notifications:
  slack:
    secure: FOdkDYnU0esUmJpHZHACrpn7OSP+2zLQ6bi9nQ1IqG3tiwUU84E7VKZj7Bm7JFcs4jQZjPhfOpiUbXnwSqu1pncwerAvDsRzDJKXLJN7I8Qa6chrZ7ztjrqUtQZxi8MA9HUwV44qc8dHOLnirGVZWsLnmJfBkA9R+jzO1pf/r+9wbkCAOYUFo6mqEYprX13LifT2HyinFaH94lxf1Mkr+TA98Ms4oTQbTMe0BgMWqIG1MKfwiExn1+LooI9ZnINtj62GrJO4Kchl8ZiDNnLrLqsV6Pk6qip/txhWWPOE5Jcq3mMO7g9I3i5Qb9mh/TaHsHqvyoiaQLn6Q+yHJFB5CZSGR9TACZV2f4FBRNU3Ezyl4Qyu/DWpgiRFOvKy/AdYdqBSYtN48raU6bvvVug+LvZKzYTtiEm2gwyjO2AeobS68fnM88nFNRUC7SE6TNrShJIKEnzOdE0zRGQ4N/nhjvQYg5mcPA+Ub9ImrcTG4+osARARCs0GnEzG+lwjWogw76lPLjXlT8hwbBDk3sJ0VUaiw5Vy7u9w+ONUVPu5J7dBSUgajvIDJob8kUtEqJW+Om9DbcaUL+xtzlUzE/3d3Loh1jx+rIrt8YfNJmMtBBZVV2c/3emVxLHAiEG1rbuE+upWbCJQT7y9Kp8R0vEZadjVKcI9P99icxQgYgMOfvU=
deploy:
  provider: pypi
  skip_cleanup: true
  user: wray
  password:
    secure: muSIs9a7d+7hHbfvUtmaY54FUkteye6O2VT8F2lsbJ3xU7kN/FrsYtHadKovYgnX3Hcl+8J7b0CvRre7vTEjXu4I/XTvuL/dL5dl6gT4QokHWtrwhk/GxpiMvO8Y7Fki3XuWxBjU8JUT7X2f9xGqE8MnFHe8XWdnpZhYdlA9TKbXPFx1zgqeIghKRuZRIb/W13m10fd8nOiKx5aw+zZmhE5K6MKgRTG6WiFnmL2HNSHtzaQvd5VD8AxqiR/aG22L0N6Y2mlHTLEpNzr3XCM22kvnAA+1v7d3clOCqxc+mIo6lpIUc1MRuXGM+LYZ6joNGS7u4/mJLyHY5QYsxxxUdgwzSBPkmN2IsMBH5lwVl8VwVJTFiT5+62sG/MwJAei4NmJamN/BOefyHf+07NuhZ6eilqn8sp8OZ0rNZrufEJVh1Q2siaQTqCYNJgyx6kAUv1AXjzhxN/aXv7UqlmsUciSTMvHyj0tXFugu2WanU/60Y1zaI0pJDEd/mXrH7HRGJqB3qA0l4pRQ+YL9Eg/GdbJNQfOBU65snpSBJ5Wem2aiR4tLOs1V6yAocUz4UncwBkPeTexwiTUnbfK6m9BaWmctHS+0sGpOpoRb/juvQcnLrDCfjwkAwO2Nio/sB25jqPBZjKm9Y1fqWulgeMzQIuKlvB1AV4W7ppRihcgqePI=
