language: python
python:
- '2.7'
install:
- pip install slackclient
- pip install urllib3
script: "./unittests"
notifications:
  slack:
    secure: FOdkDYnU0esUmJpHZHACrpn7OSP+2zLQ6bi9nQ1IqG3tiwUU84E7VKZj7Bm7JFcs4jQZjPhfOpiUbXnwSqu1pncwerAvDsRzDJKXLJN7I8Qa6chrZ7ztjrqUtQZxi8MA9HUwV44qc8dHOLnirGVZWsLnmJfBkA9R+jzO1pf/r+9wbkCAOYUFo6mqEYprX13LifT2HyinFaH94lxf1Mkr+TA98Ms4oTQbTMe0BgMWqIG1MKfwiExn1+LooI9ZnINtj62GrJO4Kchl8ZiDNnLrLqsV6Pk6qip/txhWWPOE5Jcq3mMO7g9I3i5Qb9mh/TaHsHqvyoiaQLn6Q+yHJFB5CZSGR9TACZV2f4FBRNU3Ezyl4Qyu/DWpgiRFOvKy/AdYdqBSYtN48raU6bvvVug+LvZKzYTtiEm2gwyjO2AeobS68fnM88nFNRUC7SE6TNrShJIKEnzOdE0zRGQ4N/nhjvQYg5mcPA+Ub9ImrcTG4+osARARCs0GnEzG+lwjWogw76lPLjXlT8hwbBDk3sJ0VUaiw5Vy7u9w+ONUVPu5J7dBSUgajvIDJob8kUtEqJW+Om9DbcaUL+xtzlUzE/3d3Loh1jx+rIrt8YfNJmMtBBZVV2c/3emVxLHAiEG1rbuE+upWbCJQT7y9Kp8R0vEZadjVKcI9P99icxQgYgMOfvU=
deploy:
  provider: pypi
  skip_cleanup: true
  user: wray
  password:
    secure: UzTQPa/Imo67OazIdHzq4v60vsCf5WSAOC5n2rsbpDAq0TR+/oCs0KPt+NMV3ZTrcWhKOCpUe87hSq0F+fPAD5XtxPNOwrvSREpQUcwF1KWALlYb3ckUpoD8CNxVXG87h3E3AOrRpwCNHjQGnsBkToE143LgIx/NyGPan2fV8oWAECt086MZtzhtcl87lu10B+qGF5nB6zZLNmmec4Lfm5UoJyymUBRvhwq/OjoGXHfGuLWS7X+XiO3tZrJANE8I0zzuOafvYBKnE9eKJU1jdr5J20H5fIS3H6Aeas09t40qWfiXXXzIrSBDimqvtdADJXUbygfZXyN0/GBycs/5bl6Z6nWxJ+ntMXMeHUs6KhDrsgPBv2+E+F5r9ickiT02ClY3rYPbmCf3T3VWSq6175UQ2sUN6/67YsfayMSAeb2tHcMkcxs4/NQCFD9vRCUnWwFKjVJV7XbD19GP7r90w69JqTM1iK4iYNjw4UPCeS5tM8nKVRRbxDphWnh+ZZUnOwCFtL/0jl8XxQADUn2zfgoKj3lOLWc+4vnLcwQbFJ9F6OMNjla9VwwXHsm8IxYV7VCfuIb/xUK0wYiBpuaGHXI1TRbgzXC5RQ0XoY0WAvc+EY/6z/FvuZeHtz+NT50QaV5rBG3CMx76H8jOXuOjfPLjbH3CLO+EWG0KKztEKOI=
