language: python
python:
- '2.7'
install:
- pip install slackclient
- pip install urllib3
script: ./unittests
notifications:
  slack:
    secure: 
deploy:
  provider: pypi
  skip_cleanup: true
  user: wray
  password:
    secure: 
